-- AlterTable
ALTER TABLE "Post" ADD COLUMN "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Post" ADD COLUMN "updated_at" DATETIME;

-- AlterTable
ALTER TABLE "User" ADD COLUMN "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "User" ADD COLUMN "updated_at" DATETIME;
